export enum ProjectError {
    PROJECT_ID_EMPTY = 'PROJECT_ID_EMPTY',

    PROJECT_NAME_EMPTY = 'PROJECT_NAME_EMPTY',
    PROJECT_NAME_EXISTED = 'PROJECT_NAME_EXISTED',

    PROJECT_CODE_EMPTY = 'PROJECT_CODE_EMPTY',
    PROJECT_CODE_EXISTED = 'PROJECT_CODE_EXISTED',

    PROJECT_LOCATION_EMPTY = 'PROJECT_LOCATION_EMPTY',
    PROJECT_STARTED_AT_INVALID = 'PROJECT_STARTED_AT_INVALID',
    PROJECT_IS_ORIGINAL_INVALID = 'PROJECT_IS_ORIGINAL_INVALID',

    PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',

    PROJECT_NOT_PERMISSION = 'PROJECT_NOT_PERMISSION',

    USER_NOT_BELONG_TO_PROJECT = 'USER_NOT_BELONG_TO_PROJECT',

    PROJECT_MANAGER_EMPTY = 'PROJECT_MANAGER_EMPTY',
}
