export enum SummaryError {
    SUMMARY_NOT_FOUND = 'SUMMARY_NOT_FOUND',

    SUMMARY_EXISTED = 'SUMMARY_EXISTED',

    ROUTE_ID_EMPTY = 'ROUTE_ID_EMPTY',
    ROUTE_NAME_EMPTY = 'ROUTE_NAME_EMPTY',

    STATION_ID_EMPTY = 'STATION_ID_EMPTY',
    STATION_NAME_EMPTY = 'STATION_NAME_EMPTY',

    PILLAR_ID_EMPTY = 'PILLAR_ID_EMPTY',
    PILLAR_NAME_EMPTY = 'PILLAR_NAME_EMPTY',

    PILLAR_GROUP_ID_EMPTY = 'PILLAR_GROUP_ID_EMPTY',
    PILLAR_CATEGORY_ID_EMPTY = 'PILLAR_CATEGORY_ID_EMPTY',
    PILLAR_MATERIAL_ID_EMPTY = 'PILLAR_MATERIAL_ID_EMPTY',

    SUMMARY_REPORT_INVALID_NAME = 'SUMMARY_REPORT_INVALID_NAME',
}
