export enum AuthError {
    UNAUTHORIZED = 'UNAUTHORIZED',
    BAD_CREDENTIALS = 'BAD_CREDENTIALS',
    NOT_FOUND = 'NOT_FOUND',
    TOKEN_REVOKED = 'TOKEN_REVOKED',

    MISSING_FACEBOOK_TOKEN = 'MISSING_FACEBOOK_TOKEN',
    MISSING_GOOGLE_TOKEN = 'MISSING_GOOGLE_TOKEN',
    MISSING_APPLE_TOKEN = 'MISSING_APPLE_TOKEN',
    MISSING_PLATFORM = 'MISSING_PLATFORM',
    MISSING_PROFILE_EMAIL = 'MISSING_PROFILE_EMAIL',
    PLATFROM_INVALID = 'PLATFROM_INVALID',
}
