export enum MaterialError {
    MATERIAL_ID_EMPTY = 'MATERIAL_ID_EMPTY',
    MATERIAL_NAME_EMPTY = 'MATERIAL_NAME_EMPTY',
    MATERIAL_NAME_EXISTED = 'MATERIAL_NAME_EXISTED',

    MATERIAL_NOT_FOUND = 'MATERIAL_NOT_FOUND',
    MATERIAL_EXISTED = 'MATERIAL_EXISTED',
}
