export enum BoardError {
    BOARD_EXISTED = 'BOARD_EXISTED',
    BOARD_NOT_FOUND = 'BOARD_NOT_FOUND',
    BOARD_NOT_PERMISSION = 'BOARD_NOT_PERMISSION',

    BOARD_ID_EMPTY = 'BOARD_ID_EMPTY',
    BOARD_DATE_EMPTY = 'BOARD_DATE_EMPTY',
}
