export enum TimesheetProjectError {
    TIMESHEET_PROJECT_NOT_FOUND = 'TIMESHEET_PROJECT_NOT_FOUND',
    TIMESHEET_PROJECT_EXISTED = 'TIMESHEET_PROJECT_EXISTED',

    TIMESHEET_PROJECT_ID_EMPTY = 'TIMESHEET_PROJECT_ID_EMPTY',
    TIMESHEET_PROJECT_MONTH_EMPTY = 'TIMESHEET_PROJECT_MONTH_EMPTY',
    TIMESHEET_PROJECT_DATE_EMPTY = 'TIMESHEET_PROJECT_DATE_EMPTY',

    TIMESHEET_PROJECT_NOT_PERMISSION = 'TIMESHEET_PROJECT_NOT_PERMISSION',

    TIMESHEET_PROJECT_NO_VALUE = 'TIMESHEET_PROJECT_NO_VALUE',
}
