export enum CategoryError {
    CATEGORY_ID_EMPTY = 'CATEGORY_ID_EMPTY',
    CATEGORY_NAME_EMPTY = 'CATEGORY_NAME_EMPTY',
    CATEGORY_NAME_EXISTED = 'CATEGORY_NAME_EXISTED',

    CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
    CATEGORY_EXISTED = 'CATEGORY_EXISTED',
}
