// Import Summary By Excel File
export const SUMMARY_EXCEL_SO_TRU_COL_INDEX = 0;
export const SUMMARY_EXCEL_KHOANG_CACH_THIET_KE_COL_INDEX = 1;
export const SUMMARY_EXCEL_CONG_DON_COL_INDEX = 2;
export const SUMMARY_EXCEL_SO_TRU_HOANG_CONG_COL_INDEX = 3;
export const SUMMARY_EXCEL_KHOANG_CACH_HOAN_CONG_COL_INDEX = 4;
export const SUMMARY_EXCEL_KHOANG_NEO_COL_INDEX = 5;
export const SUMMARY_EXCEL_HINH_THUC_TRU_COL_INDEX = 6;

// Export Summary to Excel
export const SUMMARY_WORKSHEET_NAME = 'Tong Ke';

export const SUMMARY_EXCEL_BODY_HEADER_START_ROW = 6;
export const SUMMARY_EXCEL_PILLAR_GROUP_ROW = SUMMARY_EXCEL_BODY_HEADER_START_ROW;
export const SUMMARY_EXCEL_BODY_PILLAR_CATEGORY_ROW = 7;
export const SUMMARY_EXCEL_BODY_PILLAR_MATERIAL_ROW = 8;
export const SUMMARY_EXCEL_BODY_DATA_START_ROW = 9;

export const SUMMARY_EXCEL_SO_TRU_COL = SUMMARY_EXCEL_SO_TRU_COL_INDEX + 1;
export const SUMMARY_EXCEL_KHOANG_CACH_THIET_KE_COL = SUMMARY_EXCEL_KHOANG_CACH_THIET_KE_COL_INDEX + 1;
export const SUMMARY_EXCEL_CONG_DON_COL = SUMMARY_EXCEL_CONG_DON_COL_INDEX + 1;
export const SUMMARY_EXCEL_SO_TRU_HOANG_CONG_COL = SUMMARY_EXCEL_SO_TRU_HOANG_CONG_COL_INDEX + 1;
export const SUMMARY_EXCEL_KHOANG_CACH_HOAN_CONG_COL = SUMMARY_EXCEL_KHOANG_CACH_HOAN_CONG_COL_INDEX + 1;
export const SUMMARY_EXCEL_KHOANG_NEO_COL = SUMMARY_EXCEL_KHOANG_NEO_COL_INDEX + 1;
export const SUMMARY_EXCEL_HINH_THUC_TRU_COL = SUMMARY_EXCEL_HINH_THUC_TRU_COL_INDEX + 1;
export const SUMMARY_EXCEL_PILLAR_START_COL = SUMMARY_EXCEL_HINH_THUC_TRU_COL + 1;
