export const TIMESHEET_WORKSHEET_NAME = 'BCC';

export const TIMESHEET_EXCEL_COLUMNS_LENGTH_EXCEPT_MEMBER_DATA = 12;
export const TIMESHEET_EXCEL_MEMBER_DATA_ROW_LENGTH = 7;

export const TIMESHEET_EXCEL_BODY_HEADER_START_ROW = 6;
export const TIMESHEET_EXCEL_BODY_DATA_START_ROW = 9;

export const TIMESHEET_EXCEL_MASO_COL = 1;
export const TIMESHEET_EXCEL_HOTEN_COL = 2;

export const TIMESHEET_EXCEL_BODY_DATA_START_COL = 3;
