export enum TimesheetUserError {
    TIMESHEET_USER_NOT_FOUND = 'TIMESHEET_USER_NOT_FOUND',
    TIMESHEET_USER_EXISTED = 'TIMESHEET_USER_EXISTED',

    TIMESHEET_USER_ID_EMPTY = 'TIMESHEET_USER_ID_EMPTY',
    TIMESHEET_USER_MONTH_EMPTY = 'TIMESHEET_USER_MONTH_EMPTY',
    TIMESHEET_USER_DATE_EMPTY = 'TIMESHEET_USER_DATE_EMPTY',

    TIMESHEET_USER_NOT_PERMISSION = 'TIMESHEET_USER_NOT_PERMISSION',

    TIMESHEET_USER_NO_VALUE = 'TIMESHEET_USER_NO_VALUE',
}
