export enum ExportError {
    TIMESHEET_MONTH_EMPTY = 'TIMESHEET_MONTH_EMPTY',

    REPORT_NAME_EMPTY = 'REPORT_NAME_EMPTY',

    EXPORT_REPORT_SOMETHING_WENT_WRONG = 'EXPORT_REPORT_SOMETHING_WENT_WRONG',
    EXPORT_SUMMARY_SOMETHING_WENT_WRONG = 'EXPORT_SUMMARY_SOMETHING_WENT_WRONG',
    EXPORT_TIMESHEET_SOMETHING_WENT_WRONG = 'EXPORT_TIMESHEET_SOMETHING_WENT_WRONG',
}
