export enum UploadError {
    MISSING_IMAGE_FILE = 'MISSING_IMAGE_FILE',
    UPLOAD_FAILED = 'UPLOAD_FAILED',
    DELETE_OBJECT_FAILED = 'DELETE_OBJECT_FAILED',
    INVALID_FILE_UPLOAD = 'INVALID_FILE_UPLOAD',
    FILE_TOO_BIG = 'FILE_TOO_BIG',
    INVALID_IMAGE_TYPE = 'INVALID_IMAGE_TYPE',

    INVALID_PROOF_FILE_NAME = 'INVALID_PROOF_FILE_NAME',
}
