export enum JobError {
    JOB_ID_EMPTY = 'JOB_ID_EMPTY',
    JOB_NAME_EMPTY = 'JOB_NAME_EMPTY',
    JOB_NAME_EXISTED = 'JOB_NAME_EXISTED',
    JOB_NOT_EXISTS = 'JOB_NOT_EXISTS',
    JOB_EXISTED = 'JOB_EXISTED',

    JOB_NOT_FOUND = 'JOB_NOT_FOUND',
}
