export enum CommonError {
    SOMETHING_WRONG_WHEN_CREATE = 'SOMETHING_WRONG_WHEN_CREATE',
    SOMETHING_WRONG_WHEN_UPDATE = 'SOMETHING_WRONG_WHEN_UPDATE',
    SOMETHING_WRONG_WHEN_DELETE = 'SOMETHING_WRONG_WHEN_DELETE',
}
